---
title: "add_instances"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("helper.R")
library(tidyverse)
library(DBI)
library(odbc)
cfg <- config::get("database", file = "config.yml")
con <- do.call(pool::dbPool, cfg)
```

```{r getting_started}
schema <- "classroom"
prefix <- "v1_"
classroomid <- 1
raw_instance_data <- readr::read_csv("spglobal-final-1.csv", col_names = c("url", "username", "password"))

```

```{r upload_instances}
pmap_dfr(raw_instance_data %>% select(url, username, password), function(url, username, password) {
  add_instance(
    con = con, schema = schema, prefix = prefix, classroomid = 1,
    identifier = url, url = url, username = username, password = password
  )
})

# clear instances if necessary
# dbGetQuery(con, glue::glue("DELETE FROM {schema}.{prefix}instance WHERE classroomid = {classroomid} RETURNING *;"))
```

```{r map_instances}
dbGetQuery(con,
           glue::glue(
             "WITH students as (
              select studentid, classroomid, row_number() over (partition by true) from {schema}.{prefix}student
              WHERE classroomid = {classroomid}
              AND studentid NOT IN (select studentid FROM {schema}.{prefix}student where classroomid = {classroomid})
             ), instances as (
              select instanceid, classroomid, row_number() over (partition by true) from {schema}.{prefix}instance
              WHERE classroomid = {classroomid}
              AND instanceid NOT IN (select instanceid from {schema}.{prefix}claim where classroomid = {classroomid})
             )
             INSERT INTO {schema}.{prefix}claim (studentid, classroomid, instanceid)
             SELECT a.studentid, a.classroomid, b.instanceid
             FROM students a
             INNER JOIN instances b on a.classroomid = b.classroomid and a.row_number = b.row_number
             RETURNING *;"
           ))

# clear claims if necessary
# dbGetQery(con, glue::glue("DELETE FROM {schema}.{prefix}claim WHERE classroomid = {classroomid} RETURNING *;"))
```
